# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - gcc-4.9
      - g++-4.9
# Build steps
script:
  - mkdir build
  - cd build
  - cmake ..
  - make